### ISSUE TITLE
Bad url generated

### ISSUE THREAD

**Issue by rezaarab** [VahidN/GitHubFolderDownloader#1]
Hello, My Github folder url is :
https://github.com/EdxStudents/W3C_HTML5.1x/tree/master/About%20W3C%20and%20the%20Web
When strat to download error logs write:
The internet connection was not found.
Finished https://api.github.com/repos/EdxStudents/W3C_HTML5.1x/contents/About%2520W3C%2520and%2520the%2520Web.

In generated url in up, space encoded to "%2520" but if it be "%20" the url is valid.

**Comment by VahidN** [comment]
Hello,
Try the [new version](https://github.com/VahidN/GitHubFolderDownloader/releases/tag/V1.1).

**Comment by rezaarab** [comment]
I contribute on your project, This is my first contribution so forgive me on fault cause.
Reza Arab

**Comment by VahidN** [comment]
Have you tested the new version? What was the problem?

**Comment by rezaarab** [comment]
@VahidN  Yes i tested last release, although doing improved URL detection is OK but internet connection is failed, because my internet connection establish through proxy server, I Fork your project and i patch bug with change in code and it's work for me perfectly, I pull request change to your repository that wait to commit by you, Please check pull request.

**Comment by VahidN** [comment]
Thanks. But that proxy setting, is not a bug. It's just a user's preference.

**Comment by rezaarab** [comment]
@VahidN Yes, Right proxy setting is user preference but it's good in ui setting not in config, Another problem is check internet connection code, My network admin reject ping request so using ping class is fault in this condition, I use **WebClient.OpenRead(url)** That may be not efficient but work even in this situation, I Push request for this scenario.

**Comment by VahidN** [comment]
You should not send too many changes in one pull request. [more info](http://www.dotnettips.info/post/2033/%d8%a2%d8%b4%d9%86%d8%a7%db%8c%db%8c-%d8%a8%d8%a7-%d8%b3%d8%a7%d8%ae%d8%aa%d8%a7%d8%b1-%db%8c%da%a9-pull-request-%d8%ae%d9%88%d8%a8).

**Comment by rezaarab** [comment]
Ok, Thanks for your attention.

**Comment by rezaarab** [comment]
@VahidN Before i change the code must be always bring up that issue first? In general where is best location for discussing on a **piece of code**?
Thanks

**Comment by VahidN** [comment]
Always create a new issue per different subject. This topic was about urls. So it shouldn't be a place for proxy and network and other things. each one of these subjects, needs a different issue/ticket.

P.S.
[Check out the new version](https://github.com/VahidN/GitHubFolderDownloader/releases)

**Comment by rezaarab** [comment]
@VahidN  I got it in first link [more info](http://www.dotnettips.info/post/2033/%d8%a2%d8%b4%d9%86%d8%a7%db%8c%db%8c-%d8%a8%d8%a7-%d8%b3%d8%a7%d8%ae%d8%aa%d8%a7%d8%b1-%db%8c%da%a9-pull-request-%d8%ae%d9%88%d8%a8) you present. I liked to contribute in this repository and first i don't know really how to begin, i study technical issue for github but i don't know how to interact with each other in this environment, i start it and until now i learned a lot thing by your guidance.
First i must be permit from you to contribute?
If i permitted this means i must first find bug and report it in issue ticket and discuss it with owner(you) and then if you accepted i or you fix the error?
Or i can fork repository and fix bugs based on my concern and then pull request commits?
I'm looking for a good way to work here in github without bungling. 
Thanks in advance.

**Comment by VahidN** [comment]
These are not mandatory. It's better to send only one change and subject in one pull request. If you send many changes, if I reject one of them, I should close the whole pull request and all of the other changes too.
So it's better to open a new issue to discuss about it. and then send the related pull request. each issue should discuss only one subject and not more.
