### ISSUE TITLE
[Request] Different branches

### ISSUE THREAD

**Issue by jmbeach** [VahidN/GitHubFolderDownloader#5]
As of right now, the program only works for the main branch. It would be cool if you could request other branches

**Comment by VahidN** [comment]
- Implemented via https://github.com/VahidN/GitHubFolderDownloader/commit/f9773b843d952b3ffe2917363e08fe4da9923dab
- [Download V1.3](https://github.com/VahidN/GitHubFolderDownloader/releases/tag/V1.3)

**Comment by jmbeach** [comment]
Awesome!
