### ISSUE TITLE
empty download and documentation problems

### ISSUE THREAD

**Issue by jonhp** [VahidN/GitHubFolderDownloader#6]
# Summary of the issue
downloaded v1.3
* my window doesn't match readme.md
* seems to work, and creates target folders; however all are empty -- no files;
  branch I selected: master
 folder url is: https://github.com/esp8266/Arduino/tree/master/doc
* 2nd bullet in readme.md; form should be from

not sure what to do/try next. 

## Environment

```
The in-use version:
Operating system: win10
IDE: (e.g. Visual Studio 2015)
```

**Comment by VahidN** [comment]
Do you have a GitHub token? If not, click here https://github.com/settings/tokens/new to create a new one. Then enter an arbitrary name here and just select the `public_repo -> Access public repositories` field. Finally click at the generate new token button. Now you can use this token to fetch new files from GitHub.

**Comment by jonhp** [comment]
yes, request was made with a new token which was authorized for all repos option.

**Comment by VahidN** [comment]
I can't reproduce your issue:
![test](https://user-images.githubusercontent.com/766010/35070065-66f31870-fbf1-11e7-9642-abbf16d1f830.png)

**Comment by jonhp** [comment]
thanks for being patient.

I exited the application and restarted it…

now it works fine.

So I can’t reproduce it either. 

I will close it out.

Jon

**Comment by jonhp** [comment]
doesn't reoccur after restarting application.
