### ISSUE TITLE
The request was aborted: could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by Khyat** [VahidN/GitHubFolderDownloader#7]
# Summary of the issue
I am using .NET 4.5 but still it's raising this issue of SSL/TLS. Can't download a single folder from any repo. Any workaround of this solution would be appreciated.

![github](https://user-images.githubusercontent.com/20352413/49986266-3178a400-ff95-11e8-9777-5b010ee67ca3.jpg)

**Comment by VahidN** [comment]
Fixed via #https://github.com/VahidN/GitHubFolderDownloader/commit/d5aeb25d57c65ab6069d4aa68d5cf4d41f974df5
[Try Version 1.3.1](https://github.com/VahidN/GitHubFolderDownloader/releases)
